# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AxKit-App-TABOO
version:      0.33
version_from: lib/AxKit/App/TABOO.pm
installdirs:  site
requires:
    Apache::AxKit::Exception:      0
    Apache::AxKit::Plugin::AddXSLParams::Request: 0
    Apache::AxKit::Plugin::Param::Expr: 0
    AxKit:                         1.62
    AxKit::XSP::BasicSession:      0.21
    AxKit::XSP::QueryParam:        0.02
    AxKit::XSP::Sendmail:          0
    Class::Data::Inheritable:      0
    Crypt::GeneratePassword:       0
    Data::Dumper:                  0
    DBD::Pg:                       1.32
    DBI:                           0
    Encode:                        2.09
    Exception::Class::DBI:         0
    Formatter::HTML::Textile:      0.5
    IDNA::Punycode:                0
    MIME::Types:                   0
    Time::Piece:                   0
    XML::LibXML:                   1.57
    XML::LibXSLT:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
