CREATE USER taboodemo  WITH PASSWORD 'hk987JKBgui';

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE categories TO taboodemo;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE comments TO taboodemo;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE stories TO taboodemo;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO taboodemo;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE contributors TO taboodemo;
